---

- name: sample playbook
  hosts: 192.168.1.1
  connection: local

  tasks:
    - name: default interfaces
      nxos_interface: interface={{ item }} state=default host={{ inventory_hostname }} transport=nxapi
      with_items:
        - Ethernet1/2
        - Ethernet1/3

    # Ensure an interface is a Layer 3 port and that it has the proper description
    - name: config interface
      nxos_interface: interface=Ethernet1/2 description='Configured by Ansible' mode=layer3 host={{ inventory_hostname }} username=admin password=admin transport=nxapi

    # Admin down an interface
    - nxos_interface: interface=Ethernet1/3 admin_state=down host={{ inventory_hostname }} username=admin password=admin transport=nxapi